### PR TITLE
Add a few readme screenshots

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Maybe we should remove the experimental mention for plotly before uploading screenshots.

**Comment by rapgenic** [comment]
I agree that it's not really good looking in a screenshot. 

Just for transparency towards you, however, I have to say that the plotly integration is quite incomplete, as it works mainly for the basic plots, and still has limitations even in the basic examples...

**Comment by SylvainCorlay** [comment]
> Just for transparency towards you, however, I have to say that the plotly integration is quite incomplete, as it works mainly for the basic plots, and still has limitations even in the basic examples...

Then let's keep the experimental mention!

**Comment by SylvainCorlay** [comment]
This is ready to go!

**Pull request merged**
