### PR TITLE
Add binder file

### PR DESCRIPTION
**Pull request by AntoinePrv**

### CODE REVIEW

**Comment by AntoinePrv** [comment]
So it looks like Octave interpreter itself is linking to OpenGl, which I believe our problem is coming from
```
jovyan@jupyter-antoineprv-2dxeus-2doctave-2dtfnbc8nl:~$ xoctave --version
xoctave: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
jovyan@jupyter-antoineprv-2dxeus-2doctave-2dtfnbc8nl:~$ octave
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
/srv/conda/envs/notebook/bin/octave-cli-7.2.0: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by AntoinePrv** [comment]
Great, we have the octave interpreter working, but not yet the plots.

**Comment by rapgenic** [comment]
Hi, I'm chiming in to share what I remember about this issue... 

It's been a few months since I last tried using xeus_octave with binder, so I might be wrong, but from what I remember the plots will not work because the glfw library present in conda forge is built for x11 support and not osmesa.

That's why I used to build the library with the cmake files.

Note that when glfw 3.4 is out this will be automatically fixed, because it supports *dynamic* loading of the appropriate backend (that can also be specified with some hints in the code). This is not the case with the current version of the library, which needs to be built with the support for a specific backend in mind.

**Comment by AntoinePrv** [comment]
Thanks for the info! Definitely this release will make things easier, but it still a bit far down the road.

In the meantime, a colleague suggested a few more tricks to try to make X11 & openGL work on binders.

**Comment by AntoinePrv** [comment]
```txt
xoctave: /home/conda/feedstock_root/build_artifacts/glfw_1658586347901/work/src/window.c:557: glfwSetWindowSize: Assertion `window != ((void *)0)' failed.
```

**Pull request merged**
