### PR TITLE
Fix memory error for PNG encoding

### PR DESCRIPTION
**Pull request by AntoinePrv**
This is on me for breaking something that was working :facepalm: 
Plots should be working on MacOS now.

### CODE REVIEW

**Comment by AntoinePrv** [comment]
Octave is still showing some warnings but seems irrelevant. @rapgenic it looks like we could silence those, right?
```
warning: opengl_renderer::render_text: support for rendering text (FreeType) was unavailable or disabled when Octave was built
warning: called from
    axes at line 107 column 8
    newplot at line 161 column 10
    surf at line 77 column 9
    sombrero at line 68 column 5
 ```

**Comment by rapgenic** [comment]
Well it's a bit strange if they weren't there before (I don't have them), I'll try pulling your changes to see if something changes.

**Comment by rapgenic** [comment]
I just built your changes and I do not see any warning... I actually don't know why it might be triggering them, possibly a missing library (e.g. freetype as reported)?

Anyways it was unlikely they were related so I think you can ignore them

**Comment by AntoinePrv** [comment]
Sorry, missing some context. They come on MacOS, when using the `conda-forge` Octave. I think it comes from there.

**Pull request merged**
